[tasks.sed]
script = '''
rg serde_json -l | xargs sd "serde_json" "serde_partiql"
'''

[tasks._version-up]
script = '''
version-make up -rz Cargo.toml
'''

[tasks.version-tag]
script = '''
git tag v$(version-make show Cargo.toml)
'''

[tasks.version-untag]
script = '''
git tag v$(version-make show Cargo.toml) -d
'''
